#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'daemon_spawn'
require 'resque'

class ResqueWorkerDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('*') # Specify which queues this worker will process
    @worker.verbose = 1 # Logging - can also set vverbose for 'very verbose'
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end
end

ResqueWorkerDaemon.spawn!({
  :processes => 5,
  :log_file => File.expand_path("log/resque_worker.log"),
  :pid_file => File.expand_path("../../shared/pids/resque_worker.pid"),
  :sync_log => true,
  :working_dir => File.expand_path("../../", __FILE__),
  :singleton => true
})