#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)
require 'daemon_spawn'
require 'resque'
require 'resque_scheduler'

if ENV['RAILS_ENV'] == "development"
  pid_file = File.expand_path("tmp/resque_worker.pid")
else
  pid_file = File.expand_path("../../shared/pids/resque_worker.pid")
end

class ResqueSchedulerDaemon < DaemonSpawn::Base
  def start(args)
    Resque::Scheduler.verbose = true
    Resque::Scheduler.run
  end

  def stop
    Resque::Scheduler.shutdown
  end
end

ResqueSchedulerDaemon.spawn!({
  :log_file => File.expand_path("log/resque_scheduler.log"),
  :pid_file => File.expand_path("../../shared/pids/resque_scheduler.pid"),
  :sync_log => true,
  :working_dir => File.expand_path("../../", __FILE__),
  :singleton => true
})